version: "3.9"

name: kexit

services:

  frontend:
    image: zaranik/kexit-frontend:local
    restart: always
    network_mode: host

  eureka:
    image: zaranik/kexit-eureka:latest
    restart: always
    network_mode: host

  gateway:
    image: zaranik/kexit-gateway:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      EUREKAHOSTNAME: localhost
      SPRING_PROFILES_ACTIVE: default,dev
    network_mode: host

  core:
    image: zaranik/kexit-core:latest
    restart: always
    environment:
      EUREKAHOSTNAME: localhost
      MONGO_DB_URL: mongodb://admin:password@mongo:27017/kexit-drive?authSource=admin
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: admin
      RABBITMQ_PASSWORD: password
      SPRING_PROFILES_ACTIVE: default,dev
    depends_on:
      mongo:
        condition: service_healthy
    network_mode: host

  converter-audio-video:
    image: zaranik/kexit-converter-audio:latest
    restart: always
    environment:
      EUREKAHOSTNAME: localhost
      SPRING_PROFILES_ACTIVE: default,dev
    network_mode: host

  converter-microsoft-office:
    image: zaranik/kexit-converter-microsoft-office:latest
    restart: always
    environment:
      EUREKAHOSTNAME: localhost
      SPRING_PROFILES_ACTIVE: default,dev
    network_mode: host

  mongo:
    image: mongo:6.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  rabbitmq:
    image: rabbitmq:3.9.7-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbit:/var/lib/rabbitmq
    network_mode: host

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
    ports:
      - "3000:3000"

  ffmpeg:
    image: surebert/docker-ffpmeg:latest
    restart: always
    volumes:
      - ./data/upload:/usr/src/app/uploads
    ports:
      - "9025:3000"
